# Generated by Django 5.2.7 on 2025-10-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
