# Generated by Django 5.2.7 on 2025-10-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0003_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('last_donate_date', models.DateField(blank=True, null=True)),
                ('last_receive_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
