# Generated by Django 5.2.7 on 2025-10-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0005_requestform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=120)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='donorform',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='firstname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='firstname',
            field=models.TextField(max_length=20),
        ),
    ]
