# Generated by Django 5.2.7 on 2025-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0006_hospitalrequestform_alter_donorform_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalrequestform',
            name='hospitalname',
            field=models.CharField(max_length=20),
        ),
    ]
