# Generated by Django 5.2.7 on 2025-10-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0007_alter_hospitalrequestform_hospitalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='role',
            field=models.CharField(choices=[('Donor', 'Donor'), ('Patient', 'Patient'), ('Hospital', 'Hospital')], default='Donor', max_length=10),
        ),
    ]
