# Generated by Django 5.2.7 on 2025-10-20 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0009_donor_donorform_approved_by_donorform_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
