# Generated by Django 5.2.7 on 2025-10-20 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0010_donorform_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenum', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('blood_group', models.CharField(max_length=5)),
                ('units', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Patient', 'Patient'), ('Hospital', 'Hospital')], default='Patient', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
