# Generated by Django 5.2.7 on 2025-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0011_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
