# Generated by Django 5.2.7 on 2025-10-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0012_alter_bloodrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorform',
            name='last_donate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorform',
            name='last_receive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
