# Generated by Django 5.2.7 on 2025-10-21 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0013_alter_donorform_last_donate_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='RequestForm',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='collection_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
