# Generated by Django 5.2.7 on 2025-10-21 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0015_donorform_user_alter_donorform_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalrequestform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
