# Generated by Django 5.2.7 on 2025-10-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0016_hospitalrequestform_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalRequestForm',
        ),
    ]
