# Generated by Django 5.2.7 on 2025-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0017_delete_hospitalrequestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
