# Generated by Django 5.2.7 on 2025-10-22 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0021_donorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='height',
            field=models.FloatField(default=0, help_text='Enter height in centimeters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='pressure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='sugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='taking_medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight',
            field=models.FloatField(default=0, help_text='Enter weight in kilograms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
