# Generated by Django 5.2.7 on 2025-10-22 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0022_remove_donorprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='disease_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='donation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Not Specified', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_donated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='medicine_details',
            field=models.TextField(blank=True, help_text='If yes, mention the medicine name and related disease', null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='sugar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
