# Generated by Django 5.2.7 on 2025-10-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0023_donorprofile_available_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='disease_history',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='sugar',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='blood_sugar',
            field=models.FloatField(default=100, help_text='Blood sugar in mg/dL'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='diastolic_pressure',
            field=models.PositiveIntegerField(default=80, help_text='Diastolic BP in mmHg'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='hemoglobin',
            field=models.FloatField(default=13.0, help_text='Hemoglobin in g/dL'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='systolic_pressure',
            field=models.PositiveIntegerField(default=120, help_text='Systolic BP in mmHg'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='cholesterol',
            field=models.FloatField(default=200, help_text='Cholesterol in mg/dL'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(help_text='Donor must be 18-65 years old'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='height',
            field=models.FloatField(help_text='Height in centimeters'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='medicine_details',
            field=models.TextField(blank=True, help_text='Specify medicine and related disease if taking any', null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='weight',
            field=models.FloatField(help_text='Weight in kilograms'),
        ),
    ]
