# Generated by Django 5.2.7 on 2025-10-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0024_remove_donorprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
