# Generated by Django 5.2.7 on 2025-10-23 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0026_hospitaldetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstock',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='collected_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
