# Generated by Django 5.2.7 on 2025-10-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0027_remove_bloodstock_collection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, unique=True),
        ),
    ]
