# Generated by Django 5.2.7 on 2025-10-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0028_alter_bloodstock_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='collected_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
