# Generated by Django 5.2.7 on 2025-10-23 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0029_alter_bloodstock_collected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='collected_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
