# Generated by Django 5.2.7 on 2025-10-23 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0030_alter_bloodstock_collected_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='available_status',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='blood_sugar',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='diastolic_pressure',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='donation_count',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='hemoglobin',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_donated_date',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='medicine_details',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='systolic_pressure',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='taking_medicine',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='weight',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='DonorEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('age', models.PositiveIntegerField(default=18)),
                ('date_of_birth', models.DateField(help_text='Donor must be 18-65 years old')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('hemoglobin', models.FloatField(default=13.0, help_text='Hemoglobin in g/dL')),
                ('systolic_pressure', models.PositiveIntegerField(default=120, help_text='Systolic BP in mmHg')),
                ('diastolic_pressure', models.PositiveIntegerField(default=80, help_text='Diastolic BP in mmHg')),
                ('blood_sugar', models.FloatField(default=100, help_text='Blood sugar in mg/dL')),
                ('cholesterol', models.FloatField(default=200, help_text='Cholesterol in mg/dL')),
                ('taking_medicine', models.BooleanField(default=False)),
                ('medicine_details', models.TextField(blank=True, help_text='Specify medicine and related disease if taking any', null=True)),
                ('last_donated_date', models.DateField(blank=True, null=True)),
                ('donation_count', models.PositiveIntegerField(default=0)),
                ('available_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
