# Generated by Django 5.2.7 on 2025-10-23 04:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0031_remove_donorprofile_available_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='blood_sugar',
            field=models.FloatField(default=100, help_text='Blood sugar in mg/dL'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='cholesterol',
            field=models.FloatField(default=200, help_text='Cholesterol in mg/dL'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1), help_text='Donor must be 18–65 years old'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='diastolic_pressure',
            field=models.PositiveIntegerField(default=80, help_text='Diastolic BP in mmHg'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='donation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='height',
            field=models.FloatField(default=170, help_text='Height in centimeters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='hemoglobin',
            field=models.FloatField(default=13.0, help_text='Hemoglobin in g/dL'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_donated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='medicine_details',
            field=models.TextField(blank=True, help_text='Specify medicine and related disease if taking any', null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='systolic_pressure',
            field=models.PositiveIntegerField(default=120, help_text='Systolic BP in mmHg'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='taking_medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight',
            field=models.FloatField(default=60, help_text='Weight in kilograms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='DonorEligibility',
        ),
    ]
